### ISSUE TITLE
用Generator生成的model字段全部是小写的，不是按照小驼峰命名方式，请问哪里需要设置吗

### ISSUE THREAD

**Issue by PngkZ** [macrozheng/mall-tiny#27]
用Generator生成的model字段全部是小写的，不是按照小驼峰命名方式，请问哪里需要设置吗，比如我数据库有个字段UserName,Model里生成的字段应该是userName，但是我项目里生成的却是username。用的直接是mall项目拉下来生成的

**Comment by tanxingzhou712** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PngkZ** [comment]
已经解决了
