### ISSUE TITLE
这里应该拼错了吧，应该是 execution(public * com.macro.mall.tiny.*CacheService.*(..)

### ISSUE THREAD

**Issue by yangblink** [macrozheng/mall-tiny#33]
https://github.com/macrozheng/mall-tiny/blob/a6d03ce9f73678872d9d75febe57280c13963865/src/main/java/com/macro/mall/tiny/security/aspect/RedisCacheAspect.java#LL27C55-L27C55

**Comment by tanxingzhou712** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
