### ISSUE TITLE
请在readme中提供admin等基础账号的登录密码

### ISSUE THREAD

**Issue by maxs-marcel** [macrozheng/mall-tiny#4]

**Comment by maxs-marcel** [comment]
我已经通过注释掉
com/macro/mall/tiny/modules/ums/service/impl/UmsAdminServiceImpl.java:105
的密码校验直接进入后台修改了密码解决的该问题.
提出该issue只是为了方便大家直接查看

**Comment by xiaohongbo407** [comment]
关注公众号可以获得用户名和密码

**Comment by tdoor** [comment]
ceshi----123456

**Comment by tanxingzhou712** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
