### ISSUE TITLE
登录时报错

### ISSUE THREAD

**Issue by fwt-ust** [macrozheng/mall-tiny#6]
用admin登录时报错：com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'com.macro.mall.model.UmsAdmin' as a subtype of `java.lang.Object`: no such class found
用ceshi登录时报错：java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
请问是什么原因，谢谢

**Comment by LDXu** [comment]
@fwt-ust  解决了吗？

**Comment by FanLiaoKevin** [comment]
同问，请问解决了吗？
